name: learning_about_b4a_dart
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  path: ^1.8.0
  dotenv: ^4.0.1
  parse_server_sdk: ^3.1.9

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
